api_platform:

    title: 'BileMo API'
    description: 'Check our products and register your clients'
    version: '1.0.0'

    collection:
        order: 'DESC'
        pagination:
            items_per_page: 20

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    http_cache:
        etag: true
        max_age: 3600
        shared_max_age: 3600
    formats:
        jsonld:
            mime_types: ['application/ld+json']

    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']

        jsonld:
            mime_types: ['application/ld+json']

    enable_swagger_ui: false