language: php
sudo: false
php:
  - '7.1'

env:
  global:
    - LC_ALL=en_US.UTF-8

script:
   - composer install
   - mkdir var/jwt
   - mv tests/private.pem var/jwt/private.pem
   - mv tests/public.pem var/jwt/public.pem
   - php bin/console doctrine:schema:create --env=test
   - php bin/phpunit
   - php bin/behat
